application: project-polygon
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.application

- url: /index\.html
  script: index.application

- url: /git
  script: git.application

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: fonts/(.*\.otf)
  static_files: fonts
  upload: fonts/(.*\.otf)
  mime_type: application/x-font-otf
- url: fonts/(.*\.woff)
  static_files: fonts
  upload: fonts/(.*\.woff)
  mime_type: application/x-font-woff
- url: fonts/(.*\.ttf)
  static_files: fonts
  upload: fonts/(.*\.ttf)
  mime_type: application/x-font-ttf
- url: fonts/(.*\.svg)
  static_files: fonts
  upload: fonts/(.*\.svg)
  mime_type: image/svg+xml

- url: /js
  static_dir: js

- url: /images
  static_dir: images

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest